### ISSUE TITLE
Adapter rewrites "Changed From" data to value "melcloud.0"

### ISSUE THREAD

**Issue by vvfrwl** [Black-Thunder/ioBroker.melcloud#98] opened 2021-05-04 23:42 UTC
Hi,
It's strange the adapter`s behavior. 
Adapter rewrites "Changed From" data to value "melcloud.0" at once.  See Objects->States view.
Example: You change the state "Power" from Admin console. You see "Changed from": "admin.0/admin". The adapter changes it to "melcloud.0" in ~1 sec. 
Looks like It`s ack confirmation.
It's impossible to understand and make interpretation in scripts who makes the changes (User or Script or Adapter).

Thank you

**Comment by Black-Thunder** [comment] 2021-05-06 10:01
At a first glance, the updated data retrieved from MELCloud is directly written back overwriting all existing values with ack=true. As a consequence "Changed from" is immediately set to "melcloud.0".

Will look further into it.

**Comment by vvfrwl** [comment] 2021-05-07 01:01
I have a more complicated bug with Node-Red and "MELCloud is directly written back overwriting all existing values with ack=true".
It`s my guess. 
If you send several commands (Mode, Fan, Power...) at one time from a script and these commands are saved in states between the first command and a result "ack=true" from melcloud, you have a random mess. Melcloud returns and rewrites some of the values.
You can see situation like:
node-red.0 -> Power(true) ack:false
melcloud.0 -> Power(false) ack:false
melcloud.0 -> Power(true) ack:true

It`s difficult to catch the bug. Results are random.
It`s visible if you use a subscription on the state. (Power example) 
In this case, you may have small loops.

A small example for Node-Red attached if you have it.

[Node-Red_ MelCloud_Bug.txt](https://github.com/Black-Thunder/ioBroker.melcloud/files/6438312/Node-Red_.MelCloud_Bug.txt)

**Comment by Black-Thunder** [comment] 2021-05-12 17:13
Just uploaded version 1.1.3 to GitHub. Could you please try if this fixes your problem?

**Comment by vvfrwl** [comment] 2021-05-12 17:31
Not so good
![image](https://user-images.githubusercontent.com/59322588/118018787-e713d100-b360-11eb-864d-be67dd97afab.png)

**Comment by vvfrwl** [comment] 2021-05-12 17:39
And again sometimes I catch situation like:
node-red.0 -> Set Power = true ack:false  (Initial event)
melcloud.0 -> return and rewrite  Power = false ack:false
melcloud.0 -> return and rewrite  Power = true ack:true

**Comment by Black-Thunder** [comment] 2021-05-12 17:55
I don't really use node-red, so I can't replicate that situation easily. Is it possible to add a small delay between the commands?
In theory, sending multiple commands simultaneously shouldn't be a problem, but maybe a delay in between can help.

**Comment by vvfrwl** [comment] 2021-05-12 19:45
1. With delays - that`s look ok.
2. The same configuration in the blockly (results in the log after one user command).
![image](https://user-images.githubusercontent.com/59322588/118035104-732ef400-b373-11eb-9196-46ac40bd83c4.png)

Logs:
5/12/2021, 10:40:38 PM.241	[warn ]: javascript.0 (20832) script.js.Developing.Test4: Initial event from User: AC Power OFF
5/12/2021, 10:40:38 PM.242	[info ]: javascript.0 (20832) script.js.Developing.Test4: getState(id=melcloud.0.devices.177098.control.mode, timerId=undefined) => {"val":3,"ack":false,"ts":1620848420673,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1620848420673}
5/12/2021, 10:40:38 PM.242	[warn ]: javascript.0 (20832) script.js.Developing.Test4: Initial event: Detected prev Mode = Cool
5/12/2021, 10:40:38 PM.243	[info ]: javascript.0 (20832) script.js.Developing.Test4: setForeignState(id=melcloud.0.devices.177098.control.fanSpeed, state={"val":3,"ack":false,"c":"script.js.Developing.Test4"})
5/12/2021, 10:40:38 PM.244	[info ]: javascript.0 (20832) script.js.Developing.Test4: setForeignState(id=melcloud.0.devices.177098.control.mode, state={"val":7,"ack":false,"c":"script.js.Developing.Test4"})
5/12/2021, 10:40:38 PM.245	[info ]: javascript.0 (20832) script.js.Developing.Test4: setForeignState(id=melcloud.0.devices.177098.control.power, state={"val":true,"ack":false,"c":"script.js.Developing.Test4"})
5/12/2021, 10:40:38 PM.246	[info ]: javascript.0 (20832) script.js.Developing.Test4: getState(id=melcloud.0.devices.177098.control.power, timerId=undefined) => {"val":false,"ack":false,"ts":1620848438237,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1620848438237}
5/12/2021, 10:40:38 PM.247	[warn ]: javascript.0 (20832) script.js.Developing.Test4: Global State:false
5/12/2021, 10:40:38 PM.263	[info ]: javascript.0 (20832) script.js.Developing.Test4: getState(id=melcloud.0.devices.177098.control.mode, timerId=undefined) => {"val":7,"ack":false,"ts":1620848438257,"q":0,"c":"script.js.Developing.Test4","from":"system.adapter.javascript.0","user":"system.user.admin","lc":1620848438257}
5/12/2021, 10:40:38 PM.264	[warn ]: javascript.0 (20832) script.js.Developing.Test4: Global State:7
5/12/2021, 10:40:38 PM.266	[info ]: javascript.0 (20832) script.js.Developing.Test4: getState(id=melcloud.0.devices.177098.control.power, timerId=undefined) => {"val":true,"ack":false,"ts":1620848438257,"q":0,"c":"script.js.Developing.Test4","from":"system.adapter.javascript.0","user":"system.user.admin","lc":1620848438257}
5/12/2021, 10:40:38 PM.267	[warn ]: javascript.0 (20832) script.js.Developing.Test4: Global State:true
5/12/2021, 10:40:38 PM.919	[warn ]: javascript.0 (20832) script.js.Developing.Test4: Initial event from User: AC Power OFF
5/12/2021, 10:40:38 PM.920	[info ]: javascript.0 (20832) script.js.Developing.Test4: getState(id=melcloud.0.devices.177098.control.mode, timerId=undefined) => {"val":7,"ack":false,"ts":1620848438257,"q":0,"c":"script.js.Developing.Test4","from":"system.adapter.javascript.0","user":"system.user.admin","lc":1620848438257}
5/12/2021, 10:40:38 PM.920	[warn ]: javascript.0 (20832) script.js.Developing.Test4: Initial event: Mode not equal Cool
5/12/2021, 10:40:38 PM.920	[info ]: javascript.0 (20832) script.js.Developing.Test4: getState(id=melcloud.0.devices.177098.control.power, timerId=undefined) => {"val":false,"ack":true,"ts":1620848438918,"q":0,"from":"system.adapter.melcloud.0","lc":1620848438918}
5/12/2021, 10:40:38 PM.921	[warn ]: javascript.0 (20832) script.js.Developing.Test4: Global State:false
5/12/2021, 10:40:38 PM.923	[info ]: javascript.0 (20832) script.js.Developing.Test4: getState(id=melcloud.0.devices.177098.control.mode, timerId=undefined) => {"val":3,"ack":true,"ts":1620848438921,"q":0,"from":"system.adapter.melcloud.0","lc":1620848438921}
5/12/2021, 10:40:38 PM.924	[warn ]: javascript.0 (20832) script.js.Developing.Test4: Global State:3
5/12/2021, 10:40:39 PM.325	[info ]: javascript.0 (20832) script.js.Developing.Test4: getState(id=melcloud.0.devices.177098.control.mode, timerId=undefined) => {"val":7,"ack":true,"ts":1620848439324,"q":0,"from":"system.adapter.melcloud.0","lc":1620848439324}
5/12/2021, 10:40:39 PM.326	[warn ]: javascript.0 (20832) script.js.Developing.Test4: Global State:7
5/12/2021, 10:41:28 PM.949	[info ]: javascript.0 (20832) script.js.Developing.Test4: getState(id=melcloud.0.devices.177098.control.power, timerId=undefined) => {"val":true,"ack":true,"ts":1620848488948,"q":0,"from":"system.adapter.melcloud.0","lc":1620848488948}
5/12/2021, 10:41:28 PM.950	[warn ]: javascript.0 (20832) script.js.Developing.Test4: Global State:true

[Blockly.txt](https://github.com/Black-Thunder/ioBroker.melcloud/files/6468721/Blockly.txt)

**Comment by vvfrwl** [comment] 2021-05-13 12:56
Hi,
Theoretically, This should resolve the bug:
- Make queue (FIFO) for user commands in the adapter.
- Apply\send next command to melcloud from the queue after receiving the acknowledgment of the previous one (if melcloud is online).
But I saw you have done it already: "implemented queue mechanism for sending requests to the cloud"
Maybe it has been broken later.

It may isn`t working with: "ignore unchanged state values to decrease network traffic" without having actual "ack" properties.
To have a "Changed From" state with information who has initiated the changes it`s good but not critical if compare with having "ack" properties.
* I tried to use "Changed From" for filtering wrong\extra changes getting from melcloud.
It`s possible to cancel "ignore unchanged state values to decrease network traffic" if we fix the main problem (with command delays or with the code changing)
Or, as a variant,  make check box settings for changing adapter behavior.

Thank you

**Comment by Black-Thunder** [comment] 2021-05-13 13:52
I've just uploaded some changes to the queue mechanism to GitHub. Could you please try again with this version?

For me, your example (JS code) works now correctly. All states are set as expected without using delays.

**Comment by vvfrwl** [comment] 2021-05-13 14:27
Please try it several times.
I have approximately the same situation without delays: random intermediate results from melcloud and random final values.
![image](https://user-images.githubusercontent.com/59322588/118139499-16354b80-b410-11eb-8b42-62681a287dfa.png)

And new one:

https://user-images.githubusercontent.com/59322588/118139843-73c99800-b410-11eb-81fe-7a796a5c0682.mp4

**Comment by Black-Thunder** [comment] 2021-05-13 14:33
Please set the adapter log level to "Silly" and attach it here.

**Comment by Black-Thunder** [comment] 2021-05-13 14:43
Ah... I've just noticed a small bug from my last change. Please try the new version from GitHub now.

**Comment by vvfrwl** [comment] 2021-05-13 15:12
It`s much better now.
The final result values are stable.
![image](https://user-images.githubusercontent.com/59322588/118144592-4cc19500-b415-11eb-9399-ea43e1e8aab1.png)

(html format)
[iobroker.2021-05-13.log](https://github.com/Black-Thunder/ioBroker.melcloud/files/6473339/iobroker.2021-05-13.log)

But features:
- not applied an "ack" from melcloud  to state
- it looks like there are several intermediate results from melcloud if a script catches a changed value and sends a command between the initial event and an "ack" reply from melcloud. (not sure that the situation presents in the log.)
I will try to catch it.

**Comment by vvfrwl** [comment] 2021-05-13 15:21
1. User operation in console: Change Mode -> 2
2. User operation in console: Change Power -> false
3. Script catch the event
4. melcloud return results for 1 and 2 operation.

Result (if user maks several operations at once): random intermediate results from melcloud and wrong final values


![image](https://user-images.githubusercontent.com/59322588/118146783-9d39f200-b417-11eb-8678-0262c4819424.png)
[iobroker.2021-05-13.log](https://github.com/Black-Thunder/ioBroker.melcloud/files/6473432/iobroker.2021-05-13.log)

**Comment by Black-Thunder** [comment] 2021-05-13 15:33
I've now added a separate queue for sending device commands, so final results should be rock solid now (hopefully). One more try please. 😉

As for the intermediate results I'll need to take a closer look when the current version produces correct final values.

**Comment by vvfrwl** [comment] 2021-05-13 15:47
Results are stable IF you have received all previous responses from melcloud before sends the initial command.
And results not stable if not.
![image](https://user-images.githubusercontent.com/59322588/118150168-eccded00-b41a-11eb-9e6b-5c2e75f2c843.png)
[iobroker.2021-05-13.log](https://github.com/Black-Thunder/ioBroker.melcloud/files/6473567/iobroker.2021-05-13.log)

**Comment by Black-Thunder** [comment] 2021-05-13 15:53
According to your log you don't seem to use the latest version from GitHub. Please re-install and try again.

**Comment by vvfrwl** [comment] 2021-05-13 15:59
Ok, I will try another way:
npm install https://github.com/Black-Thunder/ioBroker.melcloud
iobroker upload melcloud
iobroker restart melcloud
->> for info
![image](https://user-images.githubusercontent.com/59322588/118152408-54853780-b41d-11eb-8852-907f24008f9c.png)

**Comment by vvfrwl** [comment] 2021-05-13 16:04
What are you prefer for logs (screen, file or both)?

**Comment by Black-Thunder** [comment] 2021-05-13 16:07
Attaching the log file here is fine.
If using the latest version you should see entries like " Dequeuing **getDeviceInfo** remote request for device option XXX...." and "Dequeuing **setDevice** remote request for device option XXX...".

**Comment by vvfrwl** [comment] 2021-05-13 16:10
"IF you have received all previous responses from melcloud before sends the initial command." mode:
The final results are stable (twice tried) but a lot of intermediate changes.

![image](https://user-images.githubusercontent.com/59322588/118153300-69ae9600-b41e-11eb-9ab3-c3cc8e362e82.png)
[iobroker.2021-05-13.log](https://github.com/Black-Thunder/ioBroker.melcloud/files/6473668/iobroker.2021-05-13.log)

**Comment by Black-Thunder** [comment] 2021-05-14 18:36
In my opinion the changing intermediate values are to be expected as a result of the FIFO queue when sending multiple commands at once. As soon as the first command is sent to the cloud and a response is received, the remaining states will be set back to the original value for a short moment of time because the cloud doesn't know about these changes yet. When the command queue is completely processed all states should have now the desired values.

So in my view this is just a cosmetic bug or do you still experience any issues? If not, I would close this issue and release a new version.

**Comment by vvfrwl** [comment] 2021-05-14 20:25
"As soon as the first command is sent to the cloud and a response is received, the remaining states will be set back to the original value for a short moment of time because the cloud doesn't know about these changes yet."
That is logical behavior as is. It is clear. It is not a surprise.
The main problem, in this case, It is impossible to use any automation with subscriptions on states. (It is possible to use a simple button in own interface for one operation.)
We will have a lot of unpredictable results\operations if we have multiple random intermediate changes with subscriptions on states. 
I used to catch it in Node-Red. The reboot of the adapter only had been saving me.
Welcome to event-driven language, you have known. :-).
It is really difficult to filter the wrong intermediate states.

My example of the script is a small part of full automation. I have deleted 95% of the code for highlighting the bug.
I mean, the real script planned to be more complicated. 
But my case doesn`t matter.
Let's try to think globally, for other users.

The ideal case in my opinion:
"will be set back to the original value for a short moment of time because the cloud doesn't know about these changes yet."
The adapter should filter responses from melcloude, ignore "wrong" values, apply correct values\ack. It knows the request from a user\script. OR it has logic with source\timestamp priority of commands....etc

We have a timestamp of the command, We have a reply from melcloud with this timestamp or another command with another timestamp.
It is possible to verify timestamps and make decisions about "actual" value.

It is perfect but difficult for coding.


Option 2
Adapter manages "delays" between user\script and melcloud.
The adapter uses a queue. It applies\sends the next command one by one to melcloud from the queue after receiving the acknowledgment of the previous one.
+ It is invisible for users. 
+ It is independent of internet delays.
- Potentially it may have bugs because we are trying to go away from an event-driven approach with holding events (should control melcloud availability, control length of a queue) ... Maybe I am wrong.

Option 3 
Users should manage delays between commands. (Description of the "feature" in the documentation.)
- Potentially it may have bugs because delays in code should correlate with communication delays. That may be not stable.
- The user`s code should have additional "protection" for filtering potential wrong intermediate states. (Melcloud may answer much later if any internet problem)
- It is necessary to describe options for filtering potential wrong intermediate states.

Option ...

You are a creator, your time, you choose the direction ;-)
Anyway, Thank you

**Comment by Black-Thunder** [comment] 2021-05-14 22:47
Ah... OK, now I unterstand the underlying problem. 😉 

I've just modified the code according to your first option. The queue is now (still) processed one by one, but only the corresponding state value will be updated and set with ack=true. So every command in the queue will trigger only one change at a time and doesn't affect the other control states.

Could you please try again if this suits your use case? In your small example the more or less random intermediate values are gone.

**Comment by vvfrwl** [comment] 2021-05-15 11:34
Hi
For Power.
The script caught the event and started
1. The Script turned On the AC
2021-05-15 14:11:04.895 - info: javascript.0 ***** control.power, timerId=undefined) => {"val":true,"ack":false,

2. Melcloud rewrote the value
2021-05-15 14:11:05.637 melcloud.0 **** control.power:{"val":false,"ack":true,

3. Melcloud rewrote again and set the correct value
2021-05-15 14:11:06.819 - silly: melcloud.0 ***** control.power:{"val":true,"ack":true,


Final result is stable.
But we have the wrong intermediate event for Power (see section 2). 
Other statuses do not have intermediate wrong events. 
[iobroker.2021-05-15.log](https://github.com/Black-Thunder/ioBroker.melcloud/files/6486518/iobroker.2021-05-15.log)

ADD.
Small problem with npm
![image](https://user-images.githubusercontent.com/59322588/118359094-849e1900-b58a-11eb-9cba-08a21ed3df94.png)

**Comment by vvfrwl** [comment] 2021-05-15 11:43
Have you cut off a users` password for melcloud from logging?

**Comment by Black-Thunder** [comment] 2021-05-15 12:02
For power this is to be expected in your particular use case. As you are triggering on power=false and then set it immediately back to power=true, you're basically sending two commands to the queue. So the intermediate value for the power state is as designed.

From adapter's perspective it's hard to distinguish whether the first command should be ignored or not. At least not without refactoring the whole queue mechanism which I don't intend to do at the moment to be honest. 😉 

Nevertheless I think the recent changes should greatly improve the usability of the adapter for your use case.

**Comment by vvfrwl** [comment] 2021-05-15 12:18
Yes, You are right.
I have not caught that I send 2 commands at once without checking "ack".
`on({id: 'melcloud.0.devices.177098.control.power', val: false, ack: true}, async function (obj)` - It is resolve the case.
I will try the current version with more complicated scripts during the Weekend.
Thank you very much for your work.

**Comment by Black-Thunder** [comment] 2021-05-15 13:07
Great, I would appreciate if you could leave some feedback here once you've tested your scripts.
If everything's fine, I'll release an official version.

**Comment by vvfrwl** [comment] 2021-05-15 17:19
> Great, I would appreciate if you could leave some feedback here once you've tested your scripts.
> If everything's fine, I'll release an official version.

Ok

**Comment by vvfrwl** [comment] 2021-05-15 23:22
You can release a new official version and close this issue.
Events synchronization between iobroker and melcloud works perfectly now.
I have made a function evaporator auto drying for decreasing mold appearing and cleaning needs.
I did not find any bugs. I will write if I find any.
Great job, Thank you.

**Comment by Black-Thunder** [comment] 2021-05-15 23:32
Nice, glad to hear that. 😄 
Thanks for the feedback!

**Closed by Black-Thunder** 2021-05-15 23:32 UTC
Labels: bug
